In [1]:
import numpy as np
import pandas as pd
import math
import tensorflow as tf

In [0]:
!pip install tensorflow

In [0]:
!pip install keras

In [0]:
!pip install Keras-Applications

In [0]:
!pip install keras-resnet

In [0]:
image.shape, image

((200, 200),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [0]:
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread, imshow

image = imread('D:/Q1/question_1_dataset/train/train/2000.png', as_gray=True)
imshow(image)

In [0]:
image.resize(28,28,refcheck = False)

In [0]:
image.shape, image

((28, 28),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [0]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, GlobalAveragePooling2D

num_classes = 16

my_new_model = Sequential()
my_new_model.add(ResNet50(include_top=False, pooling='avg'))
my_new_model.add(Dense(num_classes, activation='softmax'))

my_new_model.layers[0].trainable = False

my_new_model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
from google.colab import files
uploaded = files.upload()


Saving train.rar to train.rar


In [0]:
get_ipython().system_raw("unrar x train")



In [0]:
train_path= 'train'
validation_path = 'train'
#test_path='D:/Q1/question_1_dataset/test/'

In [0]:
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator


In [0]:
from tensorflow.python.keras.applications.resnet50 import ResNet50

In [0]:
model = ResNet50(include_top = True,weights = "imagenet",input_tensor = None,input_shape = None,pooling = None,classes = 1000)

In [0]:
image_size = 200

data_generator_with_aug = ImageDataGenerator(
                                   horizontal_flip=True,
                                   width_shift_range = 0.2,
                                   height_shift_range = 0.2)

In [0]:
train_generator = data_generator_with_aug.flow_from_directory(
        train_path,
        target_size=(image_size, image_size),
        batch_size=24,
        class_mode='categorical')

Found 4465 images belonging to 16 classes.


In [0]:
validation_generator = data_generator_with_aug.flow_from_directory(train_path,
        target_size=(image_size, image_size),
        class_mode='categorical')

Found 4465 images belonging to 16 classes.


In [0]:
compute_steps_per_epoch = lambda x: int(math.ceil(1. * x / 24))
 
steps_per_epoch = compute_steps_per_epoch(4465)
val_steps = compute_steps_per_epoch(4465)
steps_per_epoch

187

In [0]:
my_new_model.fit_generator(
        train_generator,
        steps_per_epoch=187,
        epochs = 35,
        validation_data=validation_generator,
        validation_steps=187)

Epoch 1/35
187/187 [==============================] - 127s 677ms/step - loss: 1.3848 - accuracy: 0.5682 - val_loss: 4.0333 - val_accuracy: 0.1481
Epoch 2/35
187/187 [==============================] - 125s 671ms/step - loss: 0.7805 - accuracy: 0.7622 - val_loss: 1.6172 - val_accuracy: 0.5209
Epoch 3/35
187/187 [==============================] - 125s 670ms/step - loss: 0.5954 - accuracy: 0.8237 - val_loss: 0.5215 - val_accuracy: 0.8534
Epoch 4/35
187/187 [==============================] - 125s 671ms/step - loss: 0.4999 - accuracy: 0.8609 - val_loss: 0.8975 - val_accuracy: 0.6958
Epoch 5/35
187/187 [==============================] - 125s 670ms/step - loss: 0.4411 - accuracy: 0.8741 - val_loss: 0.7792 - val_accuracy: 0.7006
Epoch 6/35
187/187 [==============================] - 125s 668ms/step - loss: 0.4038 - accuracy: 0.8835 - val_loss: 0.3671 - val_accuracy: 0.9044
Epoch 7/35
187/187 [==============================] - 125s 666ms/step - loss: 0.3623 - accuracy: 0.8983 - val_loss: 0.3339 -

In [ ]:
#The final validation score of the trained model is 0.9466 or 94.66 %,val_loss = 0.1727 and the accuracy or the score of the model is 0.9574 or 95.74%, loss= 0.1634

In [0]:
my_new_model.save("model.h5")

In [0]:
from google.colab import files
uploaded = files.upload()


Saving test.zip to test.zip


In [0]:
!unzip test.zip

Archive:  test.zip
   creating: test/
  inflating: test/5784.png           
  inflating: test/5596.png           
  inflating: test/6098.png           
  inflating: test/6127.png           
  inflating: test/5235.png           
  inflating: test/6069.png           
  inflating: test/5573.png           
  inflating: test/4925.png           
  inflating: test/5473.png           
  inflating: test/5556.png           
  inflating: test/6221.png           
  inflating: test/4986.png           
  inflating: test/6370.png           
  inflating: test/5314.png           
  inflating: test/4724.png           
  inflating: test/6025.png           
  inflating: test/4998.png           
  inflating: test/5615.png           
  inflating: test/5225.png           
  inflating: test/5562.png           
  inflating: test/5570.png           
  inflating: test/5366.png           
  inflating: test/5265.png           
  inflating: test/5359.png           
  inflating: test/5145.png           
  inflating:

In [0]:
import cv2
import numpy as np

In [49]:
final_predictions = []
for i in range(4466,6380):
  img = cv2.imread("test" + "/" + str(i) + ".png")
  img = cv2.resize(img,(200,200))
  img = np.reshape(img,[1,200,200,3])
  final_predictions.append(my_new_model.predict_classes(img , batch_size = 24))
final_predictions


[array([0]),
 array([12]),
 array([7]),
 array([6]),
 array([3]),
 array([1]),
 array([3]),
 array([1]),
 array([13]),
 array([0]),
 array([6]),
 array([5]),
 array([8]),
 array([7]),
 array([12]),
 array([14]),
 array([15]),
 array([14]),
 array([4]),
 array([13]),
 array([14]),
 array([4]),
 array([13]),
 array([14]),
 array([3]),
 array([15]),
 array([7]),
 array([12]),
 array([8]),
 array([11]),
 array([5]),
 array([6]),
 array([10]),
 array([1]),
 array([14]),
 array([2]),
 array([1]),
 array([6]),
 array([5]),
 array([10]),
 array([8]),
 array([11]),
 array([7]),
 array([8]),
 array([14]),
 array([2]),
 array([14]),
 array([14]),
 array([14]),
 array([2]),
 array([8]),
 array([7]),
 array([15]),
 array([1]),
 array([3]),
 array([14]),
 array([2]),
 array([6]),
 array([5]),
 array([0]),
 array([5]),
 array([1]),
 array([0]),
 array([7]),
 array([4]),
 array([1]),
 array([3]),
 array([13]),
 array([4]),
 array([14]),
 array([15]),
 array([1]),
 array([12]),
 array([0]),
 array([12]

In [51]:
(final_predictions[0][0])

0

In [52]:
fp = []
for k in range(1914):
  fp.append(final_predictions[k][0] + 1)
fp

[0,
 12,
 7,
 6,
 3,
 1,
 3,
 1,
 13,
 0,
 6,
 5,
 8,
 7,
 12,
 14,
 15,
 14,
 4,
 13,
 14,
 4,
 13,
 14,
 3,
 15,
 7,
 12,
 8,
 11,
 5,
 6,
 10,
 1,
 14,
 2,
 1,
 6,
 5,
 10,
 8,
 11,
 7,
 8,
 14,
 2,
 14,
 14,
 14,
 2,
 8,
 7,
 15,
 1,
 3,
 14,
 2,
 6,
 5,
 0,
 5,
 1,
 0,
 7,
 4,
 1,
 3,
 13,
 4,
 14,
 15,
 1,
 12,
 0,
 12,
 7,
 0,
 8,
 13,
 8,
 12,
 7,
 15,
 9,
 13,
 4,
 14,
 1,
 10,
 6,
 6,
 12,
 10,
 5,
 6,
 1,
 13,
 9,
 2,
 14,
 8,
 13,
 10,
 6,
 12,
 7,
 5,
 11,
 8,
 2,
 10,
 0,
 3,
 1,
 3,
 4,
 10,
 0,
 7,
 0,
 10,
 11,
 14,
 1,
 3,
 15,
 14,
 4,
 13,
 15,
 7,
 12,
 7,
 0,
 3,
 1,
 15,
 14,
 4,
 13,
 6,
 6,
 14,
 0,
 6,
 5,
 0,
 10,
 15,
 9,
 2,
 4,
 8,
 5,
 11,
 6,
 11,
 10,
 8,
 2,
 4,
 15,
 9,
 0,
 10,
 13,
 3,
 1,
 3,
 1,
 12,
 10,
 0,
 12,
 7,
 15,
 3,
 13,
 4,
 14,
 13,
 4,
 14,
 15,
 12,
 7,
 8,
 0,
 10,
 6,
 5,
 2,
 9,
 14,
 0,
 11,
 5,
 6,
 11,
 8,
 4,
 2,
 9,
 15,
 0,
 15,
 4,
 2,
 8,
 11,
 2,
 4,
 15,
 9,
 11,
 8,
 8,
 11,
 15,
 9,
 2,
 4,
 0,
 2,
 6,
 5,
 11,
 0,
 1

In [53]:
Index = []
for j in range(4466,6380):
  Index.append(str(j))
Index

['4466',
 '4467',
 '4468',
 '4469',
 '4470',
 '4471',
 '4472',
 '4473',
 '4474',
 '4475',
 '4476',
 '4477',
 '4478',
 '4479',
 '4480',
 '4481',
 '4482',
 '4483',
 '4484',
 '4485',
 '4486',
 '4487',
 '4488',
 '4489',
 '4490',
 '4491',
 '4492',
 '4493',
 '4494',
 '4495',
 '4496',
 '4497',
 '4498',
 '4499',
 '4500',
 '4501',
 '4502',
 '4503',
 '4504',
 '4505',
 '4506',
 '4507',
 '4508',
 '4509',
 '4510',
 '4511',
 '4512',
 '4513',
 '4514',
 '4515',
 '4516',
 '4517',
 '4518',
 '4519',
 '4520',
 '4521',
 '4522',
 '4523',
 '4524',
 '4525',
 '4526',
 '4527',
 '4528',
 '4529',
 '4530',
 '4531',
 '4532',
 '4533',
 '4534',
 '4535',
 '4536',
 '4537',
 '4538',
 '4539',
 '4540',
 '4541',
 '4542',
 '4543',
 '4544',
 '4545',
 '4546',
 '4547',
 '4548',
 '4549',
 '4550',
 '4551',
 '4552',
 '4553',
 '4554',
 '4555',
 '4556',
 '4557',
 '4558',
 '4559',
 '4560',
 '4561',
 '4562',
 '4563',
 '4564',
 '4565',
 '4566',
 '4567',
 '4568',
 '4569',
 '4570',
 '4571',
 '4572',
 '4573',
 '4574',
 '4575',
 '4576',
 

In [0]:
Predictions_Dataframe = pd.DataFrame()

In [0]:
Predictions_Dataframe["Index"] = Index

In [0]:
Predictions_Dataframe["Categories"] = fp

In [57]:
Predictions_Dataframe

Index  Categories
0     4466           0
1     4467          12
2     4468           7
3     4469           6
4     4470           3
...    ...         ...
1909  6375          14
1910  6376           4
1911  6377          13
1912  6378           9
1913  6379           1

[1914 rows x 2 columns]

In [58]:
from google.colab import drive
drive.mount('drive')

Mounted at drive


In [0]:
Predictions_Dataframe.to_csv("Submission.csv")
!cp Submission.csv "drive/My Drive/"